### ISSUE TITLE
Application crashes when opening "Command" view

### ISSUE THREAD

**Issue by nike4613** [microsoftfeedback/WinDbg-Feedback#157]
At startup, the "Command" view is not visible. 
![image](https://github.com/microsoftfeedback/WinDbg-Feedback/assets/10411129/433406ff-5121-44a3-beb3-65421d1389e6)
Navigating to "View" > "Command" causes the application to crash.

EventLog shows an uncaught exception:
```
Application: DbgX.Shell.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The ViewManager.ActiveView must be a View contained within the ViewManager.WindowProfile.
   at Microsoft.VisualStudio.PlatformUI.Shell.ViewManager.SetActiveView(View view, ActivationType type)
   at Microsoft.Performance.Shell.WpaView.Activate()
   at DbgX.Shell.ToolWindowManager.<>c__DisplayClass22_0.<ActivateToolWindow>b__1()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at DbgX.Shell.Program.Main()
```
and a following Application Error entry:
```
Faulting application name: DbgX.Shell.exe, version: 1.2308.2002.0, time stamp: 0x63558578
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3393, time stamp: 0x6b4de7c9
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process id: 0xd578
Faulting application start time: 0x01da3dd408c880e6
Faulting application path: C:\Program Files\WindowsApps\Microsoft.WinDbg_1.2308.2002.0_x64__8wekyb3d8bbwe\DbgX.Shell.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 45c76237-53ff-479a-ad31-1704c9add5e0
Faulting package full name: Microsoft.WinDbg_1.2308.2002.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: Microsoft.WinDbg
```

This behavior persists after fully purging and reinstalling the package.

**Comment by lzybkr** [comment]
If you can share the files under `%LOCALAPPDATA%\dbg`, that might help us diagnose the issue.
After sharing those files, it's worth deleting them to see if the problem goes away.

**Comment by nike4613** [comment]
At some point, having not done anything in particular (possibly a Windows update?), it fixed itself, and I can no longer reproduce. I can send that anyway, if you think it will help.

**Comment by lzybkr** [comment]
Since it's no longer crashing and this is the only report I've seen with this stack, it's not worth investigating so I'll go ahead and close the issue.
